# Generated by Django 2.2.4 on 2021-04-28 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_to_orm_app', '0002_dojo_ninja'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ninja',
            old_name='dojo_id',
            new_name='dojo',
        ),
    ]
