# Generated by Django 2.2.4 on 2021-04-28 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_to_orm_app', '0003_auto_20210428_1757'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='dojo antiguo', max_length=255),
        ),
    ]
