# Generated by Django 2.2.4 on 2021-04-28 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_to_orm_app', '0006_auto_20210428_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='desc',
            new_name='description',
        ),
    ]
