# Generated by Django 2.2.4 on 2021-04-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sql_to_orm_app', '0007_auto_20210428_1935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='description',
            new_name='desc',
        ),
    ]
