# Generated by Django 2.2.4 on 2021-04-28 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_to_orm_app', '0008_auto_20210428_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='notas',
            field=models.CharField(default='', max_length=255),
        ),
    ]
