# Generated by Django 2.2.4 on 2021-05-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sql_to_orm_app', '0010_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=255),
        ),
    ]
